version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8085:8080"

    volumes:
      - keycloak-volume:/opt/keycloak/data

volumes:
  keycloak-volume:
